kind = "api"
previewPath = "/"
title = "telegram-scholarship-api"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8000
name = "telegram-scholarship-api"
paths = ["/"]

[services.development]
run = "cd ../.. && uv run uvicorn main:app --host 0.0.0.0 --port $PORT"

[services.production]

[services.production.run]
args = ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

[services.production.run.env]
PORT = "8000"

[services.production.health.startup]
path = "/api/healthz"
